name: Secrets Scan

on:
  pull_request:

jobs:
  scan:
    uses: AirHelp/gh-actions/.github/workflows/secrets-scan-on-pr.yaml@master
    with:
      application_name: ${{ github.event.repository.name }}
      team_name: developers
    secrets: inherit
